[phases.setup]
nixPkgs = ['nodejs_22', 'npm-9_x']

[phases.install]
cmds = ['npm ci --legacy-peer-deps']

[phases.build]
cmds = [
  'rm -rf backend/dist',
  'rm -rf backend/node_modules/.cache', 
  'npm run build:fast'
]

[start]
cmd = 'cd backend && chmod +x start-railway.sh && ./start-railway.sh'
