[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["cd backend && npm install --legacy-peer-deps"]

[phases.build]
cmds = ["cd backend && npm run railway:build"]

[start]
cmd = "cd backend && chmod +x start-railway.sh && ./start-railway.sh"

[build]
builder = "NIXPACKS"

