[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["cd backend && npm install"]

[phases.build]
cmds = ["npm run railway:build", "cd backend && npx prisma migrate deploy"]

[start]
cmd = "cd backend && npm start"

[build]
builder = "NIXPACKS"
