services:
  # Backend + Frontend Combined Service
  - type: web
    name: collabotree
    runtime: node
    plan: free
    region: oregon
    buildCommand: npm run build:all
    startCommand: npm run start:prod
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 4000
      - key: DATABASE_URL
        fromDatabase:
          name: collabotree-db
          property: connectionString
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: JWT_ACCESS_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: BCRYPT_ROUNDS
        value: 12
      - key: CLIENT_ORIGIN
        sync: false

databases:
  - name: collabotree-db
    databaseName: collabotree
    user: collabotree
    plan: free

