[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = ["npm ci --legacy-peer-deps || npm install"]

[phases.build]
cmds = [
  "echo '=== Building Frontend ==='",
  "cd ../client",
  "npm ci --legacy-peer-deps || npm install",
  "npm run build",
  "echo '=== Copying Frontend to Backend ==='",
  "cd ../backend",
  "mkdir -p dist",
  "cp -r ../client/dist dist/dist",
  "echo '=== Building Backend ==='",
  "npx prisma generate",
  "npm run build",
  "echo '=== Build Complete ==='"
]

[start]
cmd = "node dist/server.js"

